apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-azure-demo
spec:
  replicas: 2           # two replicas for high availability
  template:
    spec:
      containers:
        - name: api
          imagePullPolicy: Always   # always pull latest from registry
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "250m"
              memory: "256Mi"
