apiVersion: v1
kind: ConfigMap
metadata:
  name: k8s-azure-demo-config
  namespace: k8s-azure-demo
data:
  APP_VERSION: "1.0.0"
  PORT: "3000"
  DB_PROVIDER: "postgres"
  DB_HOST: "postgres"
  DB_PORT: "5432"
  DB_NAME: "itemsdb"
