apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: k8s-azure-demo
  labels:
    app: postgres
spec:
  type: ClusterIP
  selector:
    app: postgres
  ports:
    - name: postgres
      protocol: TCP
      port: 5432
      targetPort: 5432
